# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7674f6f72aaf44641b379e842b849bc053ff57bcd13982c61f19382833eb0bbde2404a9d19b6a4d3defc10c590c5c5e0f4e0a562500256dd1828503def9754

test:
  secret_key_base: 01177a26f5d6d892e07c09e36fd12ffd19397793cbcd37a917cec753abf36b0fcb124dc427ccff3ab9f1d30038f594bf9f57c4f5487a9d9c9c5b8f8737faa5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
